### PR TITLE
Failsafe for contig id list

### PR DESCRIPTION
**Pull request by jayrbolton**
Related ticket: https://kbase-jira.atlassian.net/browse/PUBLIC-729

This is not a bugfix for the underlying problem, but might allow the landing page to at least render instead of all-out crashing.

### CODE REVIEW

**Review by briehl — APPROVED** [review]

**Review by briehl — CHANGES_REQUESTED** [review]
Bump the version in kbase.yml please.

**Comment by jayrbolton** [comment]
:heavy_check_mark: bumped patch version

**Comment by jayrbolton** [comment]
I'm also adding a small test case for this PR real quick.

**Comment by jayrbolton** [comment]
Okay done.

**Review by briehl — APPROVED** [review]

**Pull request merged**
