### PR TITLE
Remove dependency on data_api

### PR DESCRIPTION
**Pull request by JamesJeffryes**

### CODE REVIEW

**Review by scanon — COMMENTED** [review]
Overall this looks good.  So much more clean.

I think the old data api could deal with some of the old Contig objects too.  I wonder if we need to add some support for that.  I'm not sure if there are a lot of those in the system though.  So we could add it if people report problems.

**Comment by JamesJeffryes** [comment]
It did but I think those objects are pretty rare now. This should fail "cleanly" in that it will return None for missing data in ContigSets

**Comment by MrCreosote** [comment]
I can run a query in about 5m that'll tell you exactly how many of each type are in the system if you want.

**Review by scanon — APPROVED** [review]

**Comment by scanon** [comment]
We should rework those tests at some point.  That is my fault.

**Pull request merged**
